### ISSUE TITLE
Missing aarch64 binaries

### ISSUE THREAD

**Issue by mnasiadka** [inovex/prometheus-libvirt-exporter#25]
Is it possible to publish also aarch64 binaries?

It probably could be achieved with cross compiling or something similar.

Up until now - we (OpenStack Kolla) have been compiling Tinkoff from source, if aarch64 binaries would be available - we would gladly switch to them.

**Comment by frittentheke** [comment]
@mnasiadka thanks for considering our reworked exporter for OpenStack Kolla.
Please check out https://github.com/inovex/prometheus-libvirt-exporter/releases/tag/v1.5.2 which now has arm, arm64 and also riscv builds.

If it helps you any, I could also do a multi-platform container image (amd64  + arm64) .

**Comment by frittentheke** [comment]
@mnasiadka we now reworked all of the artefact naming templates (to align better with other exporters) and also build for even more archs. Additionally we create amd64, arm64 and riscv64 container images and provide them via multi-platform image.

all of this went into https://github.com/inovex/prometheus-libvirt-exporter/releases/tag/v1.6.0
